name: Update Vault configs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to update."
        type: choice
        required: true
        default: dev
        options:
          - dev
          - prod

permissions:
  contents: read
  id-token: write

jobs:
  create_runner:
    name: Create Self-Hosted Runner
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        index: [1]
      fail-fast: true
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Start GitHub Runner
        id: start_runner
        uses: ./.github/workflows/runner
        with:
          aws_region: ${{ vars.AWS_REGION }}
          iam_role_arn: ${{ vars.IAM_ROLE }}
          ecs_cluster_name: ${{ vars.ECS_CLUSTER_NAME }}
          ecs_task_definition: ${{ vars.ECS_TASK_DEFINITION }}
          ecs_container_name: githubrunner
          ecs_task_subnet_id: ${{ vars.SUBNET_ID }}
          ecs_task_sec_group: ${{ vars.SEC_GROUP_ID }}
          pat_token: ${{ secrets.BOT_TOKEN }}

  install_and_run_terraform:
    runs-on: [self-hosted, "run_id:${{ github.run_id }}"]
    environment: ${{ inputs.environment }}
    needs: create_runner
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
          persist-credentials: false
      # https://github.com/hashicorp/setup-terraform/issues/84#issuecomment-800515442
      - name: Install NodeJS as terraform action dep
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.IAM_ROLE }}
      - name: Read terraform version
        id: read-version
        shell: bash
        working-directory: src/infra/vault
        run: |
          echo "TERRAFORM_VERSION=`cat ../../.terraform-version`" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        id: init
        working-directory: src/infra/vault
        run: |
          ./terraform.sh init ${{ inputs.environment }}

      - name: Terraform Plan
        id: plan
        working-directory: src/infra/vault
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          ./terraform.sh plan ${{ inputs.environment }}

      - name: Apply
        uses: ./.github/workflows/apply
        with:
          env: ${{ inputs.environment }}
          working-directory: src/infra/vault
          vault-token: ${{ secrets.VAULT_TOKEN }}

  delete_runner:
    name: Delete Self-Hosted Runner
    needs: [create_runner, install_and_run_terraform]
    strategy:
      matrix:
        index: [1]
      fail-fast: true
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}

    steps:
      - name: Stop Github Runner
        id: stop_runner
        uses: pagopa/interop-github-runner-aws-cleanup-action@main
        with:
          aws_region: ${{ vars.AWS_REGION }}
          iam_role_arn: ${{ vars.IAM_ROLE }}
          ecs_cluster_name: ${{ vars.ECS_CLUSTER_NAME }}
          pat_token: ${{ secrets.BOT_TOKEN }}
